### ISSUE TITLE
OSS文件上传失败！

### ISSUE THREAD

**Issue by zxcsjf** [besscroft/pisces-cloud#72]
图片选了jpg和png都试过，大小没有超过5M，是不是调用的阿里云或者其他服务，过了没有续费导致的？

**Comment by besscroft** [comment]
众所周知，这类服务一旦对公网公开，必定会被人搞，所以。。。文件的访问是公开的，但是针对 OSS 的上传，是私有的，不想被人跑脚本批量上传。
