### ISSUE TITLE
新增要用更新操作吗？

### ISSUE THREAD

**Issue by memoryFade** [besscroft/pisces-cloud#83]
https://github.com/besscroft/pisces-cloud/blob/0a6fb686a9309b95c174b2ae665a6ca9bef1c61e/pisces-admin/admin-boot/src/main/java/com/besscroft/pisces/admin/service/impl/DepartServiceImpl.java#L63

新增操作要用update吗，不应该insert吗

**Comment by besscroft** [comment]
是我写错了，感谢反馈~
